level: debug
development: true
disableCaller: false
disableStacktrace: true
encoding: console
encoderConfig:
  messageKey: M
  levelKey: L
  timeKey: T
  nameKey: 'N'
  callerKey: C
  stacktraceKey: S
  levelEncoder: capitalColor
  timeEncoder: "2006-01-02 15:04:05"
  durationEncoder: string
  callerEncoder: full
outputPaths:
  - stderr
errorOutputPaths:
  - stderr
filterSuffix:
  - "--grpc-component"
#initialFields:
#  name: test
