app:
  project: "lug"
  name: "lug"
  version: "v0.0.1"
  home: ""
  debug: true
  watcher: false
watcher:
  driver: "noop"
  name: "default"
recovery:
  enabled: true
mux:
  debug: true
task_entry:
  enabled: true
  broker: "nsq"
  consumers:
    - driver: nsq
      name: default
rest_entry:
  enabled: true
  prefork: false
  server_header: ""
  strict_routing: false
  case_sensitive: false
  immutable: false
  unescape_path: false
  etag: false
  body_limit: 4194304
  concurrency: 262144
  read_timeout: 0
  write_timeout: 0
  idle_timeout: 0
  read_buffer_size: 4096
  write_buffer_size: 4096
  compressed_file_suffix: .fiber.gz
  proxy_header: ''
  get_only: false
  disable_keepalive: false
  disable_default_date: false
  disable_default_content_type: false
  disable_header_normalizing: false
  disable_startup_message: true
  reduce_memory_usage: false
  views:
    dir: ""
    ext: ".html"
ws:
  enabled: true
  configs:
    default:
      origins: ["*"]
redis:
  enabled: true
  codis:
    addr: "127.0.0.1:6379"
    password: "foobared"
    db: 0
  redisSale:
    addr: "127.0.0.1:6379"
    password: "foobared"
    db: 0
  redisApiBusinessTwo:
    addr: "127.0.0.1:6379"
    password: "foobared"
    db: 0
  redlock_0:
    addr: "127.0.0.1:6379"
    password: "foobared"
    db: 0
mongodb:
  enabled: true
  default:
    url: "mongodb://localhost:8080"
nsq:
  default:
    address: "localhost:4150"
    lookup: ["nsqlookup-001.service.local:4161","nsqlookup-002.service.local:4161","nsqlookup-003.service.local:4161"]
  test_shanghai:
    address: "localhost:4150"
    lookup: ["nsqlookup-001.service.local:4161","nsqlookup-002.service.local:4161","nsqlookup-003.service.local:4161"]
http:
  test: ""

db:
  default:
    driver: "sqlite3x"
    source: "./sqlite.db"

registry:
  driver: "mdns"
  ttl: "5s"
tracing:
  driver: "jaeger"
  serviceName: "test"
  disabled: true