metric:
  driver: "prometheus"
  interval: 5s

db:
  table_prefix: "buzz_"
  driver: "postgres"
  driver_config:
    dsn: "host=localhost dbname=postgres user=postgres password=postgres sslmode=disable"

logger:
  level: debug
  as_json: false

http:
  base_url: /test
  enable_print_router: true
