builds:
  - main: ./cmds/lava/main.go
    id: lava
    binary: lava
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -X 'github.com/pubgo/lava/version.BuildTime={{ .Date }}'
      - -X 'github.com/pubgo/lava/version.CommitID={{ .Commit }}'
      - -X 'github.com/pubgo/lava/version.Version={{ .Version }}'
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    replacements:
      amd64: x86_64