builds:
  - main: ./cmd/lava/main.go
    id: lava
    binary: lava
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -X 'github.com/pubgo/lava/version.BuildTime={{ .Date }}'
      - -X 'github.com/pubgo/lava/version.CommitID={{ .Commit }}'
      - -X 'github.com/pubgo/lava/version.Version={{ .Version }}'
  - main: ./cmd/protoc-gen-lava/main.go
    id: protoc-gen-lava
    binary: protoc-gen-lava
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
  - main: ./cmd/protoc-gen-errors/main.go
    id: protoc-gen-errors
    binary: protoc-gen-errors
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
  - main: ./cmd/protoc-gen-resty/main.go
    id: protoc-gen-resty
    binary: protoc-gen-resty
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    replacements:
      amd64: x86_64