create_table: "CREATE TABLE if not exists %s (%s VARCHAR(%d) PRIMARY KEY)"
create_migration: "INSERT INTO %s (%s) VALUES (?)"
drop_migration: "DELETE FROM %s WHERE %s = ?"
list_migration: "SELECT %s FROM %s"
