resources:
  - resources/grpc.yaml

app:
  addr: ":8080"
  debug: true

gid-client:
  addr: localhost:50051
  srv: gid

logger:
  level: debug
  as-json: false

metric:
  driver: "prometheus"
  interval: 5s
