resources:
  - resources/grpc.yaml

app:
  addr: ":8080"
  debug: true

gid-client:
  service:
    addr: localhost:50051
    name: gid

logger:
  level: debug
  as_json: false

metric:
  driver: "prometheus"
  interval: 5s
