resources:
  - resources/grpc.yaml

app:
  addr: ":8080"
  debug: true

grpcc:
  - name: test-grpc
    registry: "mdns"
#    addr: "localhost:8080"
registry:
  driver: "mdns"
tracing:
  driver: "jaeger"

logger:
  level: debug
  as-json: false

metric:
  driver: "prometheus"
  interval: 5s
