services:
  nats:
    container_name: nats
    image: nats:latest
    restart: unless-stopped
    env_file: ${PWD}/.env
    volumes:
      - $PWD/data/nats/nats.conf:/etc/nats/nats.conf
      - $PWD/data/nats/jetstream:/data/jetstream
    command: "-c /etc/nats/nats.conf"
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    extra_hosts:
      - "host.docker.internal:host-gateway"
